fixes sentry errors
Notalib/nativescript-audioplayer pull request #11
Opened 2020-03-04 10:28 UTC by m-abs

- crashed on android with used deleted object
- crashed on older android with missing media button handler

2020-03-04 12:42 UTC, 838 approved these changes
LGTM 👍

2020-03-04 15:02 UTC, ddfreiling requested changes
Nice work, some minor corrections & questions.

2020-03-04 15:02 UTC, ddfreiling commented on src/media-service.android.ts
> +          this.exoPlayer.setForegroundMode(true);
Not sure if we even need this, read docs on https://exoplayer.dev/doc/reference/com/google/android/exoplayer2/SimpleExoPlayer.html#setForegroundMode-boolean-

2020-03-04 15:02 UTC, ddfreiling commented on src/media-service.android.ts
> +        if (shouldBeInForeground === this._isForegroundService) {
`if (!shouldBeInForeground || this._isForegroundService)` would have made more sense and make below check on `shouldBeInForeground` unnecessary.

2020-03-04 15:02 UTC, ddfreiling commented on src/media-service.android.ts
> +        this.exoPlayer?.setForegroundMode(false);
Already did that.

2020-03-04 15:02 UTC, ddfreiling commented on src/media-service.android.ts
> +        this.stopForeground(false);
Sending true as param here will remove the notification. Maybe we should do that on `STATE_ENDED` ?

2020-03-04 15:02 UTC, ddfreiling commented on src/platforms/android/include.gradle
> +  // implementation "com.google.android.exoplayer:extension-cast:$exoplayerVersion"
can remove comments

2020-03-04 17:21 UTC, m-abs commented on src/media-service.android.ts
> +        if (shouldBeInForeground === this._isForegroundService) {
I'm not sure I understand.

Here we check if we already are in the wanted state, the check below is meant to start or stop the foreground service.

2020-03-04 17:50 UTC, ddfreiling commented on src/media-service.android.ts
> +        if (shouldBeInForeground === this._isForegroundService) {
Ah, I didn’t read far enough down in the method. It’s good as it is

2020-03-04 17:51 UTC, ddfreiling commented
LGTM now, did you agree that `setForegroundMode` was not necessary for audio playback?

2020-03-05 12:08 UTC, m-abs commented
> LGTM now, did you agree that `setForegroundMode` was not necessary for audio playback?

The reference implementation in `android/uamp` doesn't use it, so I assume it is not needed.

2020-03-05 12:09 UTC, merged